version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 540383637988.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=540383637988.dkr.ecr.ap-south-1.amazonaws.com/service2
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t service2 .
      - docker tag service2:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"service2","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
